# Site settings
title: Gabriel Maus
email: gabriel.vmaus@gmail.com
url: https://github.com/kchz
description: "Backend Developer"
skills: "Desenvolvedor Backend"
meta_author: Maus Gabriel

# Google webmaster tools
google_verify: OC0F9o0iFMhxu20qkyBQ8jLQcOtDCeWpDweFbBufvQA

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: default

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a334c
  primary-rgb: "128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/gabriel.maus
  - title: github
    url: https://github.com/kchz
  - title: linkedin
    url: https://br.linkedin.com/in/gabrielmaus

# Postal address (add as many lines as necessary)
address:

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
